services:
  - type: web
    name: agripredictml
    env: python
    runtime: python-3.11.7
    rootDir: mlservices
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT